language: node_js
node_js:
- 6.11.0
- 8.1.1
script:
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: lonly197@qq.com
  api_key: c3c7c34f-604a-4867-b81b-7a91b1ffc1cb
    secure: R6LaEV6pzVs0ShJmneo+X6hcRsMVMDxL2AvEi/VBkNNygnY4nMtUpIt1HdrQjSJ95Ts54sIOB3+nckeutuFSp0ra5eZmgpkgefJv7d32AGigQA/KJAL3B1J3r+Fh6L2QO06eEeZVUbp16aT/huTHsa8I0bUpFQ8B70TvAAUm08uPtED/wiubU/czHkd7ZhMxDDceFreVrznBkdh2Xzvsp9Z85AU4ZXxuXD0UYELqJZSbXLk8aHofJw+hPmLLBUXyyeYHoHnCnGYh46xm6ZVYwbAOFxTN++HlKMWC7blwvZyVySCYRYNcpzJZ0u/Ehfvizm6fiWnQK00h6+0Ks1M3JXVWdg7jys10ccHQc5PZQSIaKAGGBjJ/pYGM013whCMcvjoUDfPOEGoETpc1KaoTMWct7AvTEO9A+p3mRzdxAhaPEt37/J7FR0A7Xh/ze6IvcQjTBoVnESnWANUfMMyl1bSsuutMi/Z+LTkJhhALGBFoUwgxrp3Ly3AvZ4rA/GRMd7Z/cjNH+jC2FmtYbYlP1EdeNcrcGBddT0eHvWDq5ypZwDgSrRzIacfdunDEdPdaZEFL9ezKfFT73tnHDczTFZk0uXDUyTuAX8lZIriDej91PaB0fjo7/9uRmLrF+AB7WPy1ggzs1ZF9NUBTV40ifjkW4x/ZfYkQhybg768fObw=
  on:
    tags: true
    repo: lonly197/cachejs
