language: node_js
node_js:
- 6.11.0
- 8.1.1
script:
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: lonly197@qq.com
  api_key:
    secure: MdXVPsCvAsRW1sW5AB++E0omVzxNkhH+6/UC8ZSgEWXuycekg/uqdP6PaDhuwj3aT0meG3ReVVsdJSYHIQ0eA0UUcLJzw2heD1fMs5seIPbvXJ/IF4pHwQvtm02aPXD0Qk0HvpMgTppuEPNh4daI/RI/LQevuQNMdGXta5Jtp7ptaNb0dxNtOJCTE0fo/LjEOded6gDywTpF9xxKHPbVnmAcNYCiIgfl7Yyq8fn76Sbyi2ITaDqrOH5DwP37EH+AElBeQDxZ16ZrzXu2+3+qv3SYk6zW4BeL3ojnMlqzLjN4xRA6H/kfKbzgfshZgvGnUc+WFfTKeArMDgJp5/ck8liWgyDLlnnjeb7ww5a9HFQslgmd6RxYYCc8G9K8WSt8oxmLHEcYyGfp9Og/yaTvvoZKJDRitGJIiAjgVrZNObiXdqUrgjNeGtnLKf7/DLtSt75vRvGYTz6pVTAiTVQmo71T2uEopZZoaq1n+/zwyHbhWjAsBgdWpMBloxnyhPCV7B8JRtyqin+0qdYXTMNAvqBWMHYt1DoL/KCvEe0w+jPXZqe8x9CxJi2QWB6Q3kKNWwuNPUq+9Lcvq/7X+evmIMLgQQ3JAhqILYyhGdL7oNnmQKZ1AW4RU+b4SeAEnFahaPCVdwQ5nR6F6iFYYle/c5OGT6gGIJbAo1D4DzMPSs0=
  on:
    tags: true
    repo: lonly197/cachejs
